### ISSUE TITLE
Create a widget wrapper

### ISSUE THREAD

**Issue by admwx7** [Hackception/Widgetception#12]
We need a wrapper to house the line chart, it should display the data from the API:
- headline
- [subheader]
  Pass the know data to the graph and instantiate it
- x-axis label
- x-axis min/max
- x-axis step
- y-axis label
- y-axis min/max
- y-axis step
- true line
- heatmap
  Trigger functions provided from the graph based on user actions

**Comment by stramel** [comment]
Mostly complete pending d3 chart, styling, and fixing issues of tie ins.
